name: mrp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"  # Ensure this is compatible with your SDK

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.2.0  # Downgraded lottie version
  animated_splash_screen: ^1.3.0
  get: ^4.7.2
  firebase_database: ^11.3.2
  firebase_core: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  firebase_core: ^3.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/welcomepage_images/welcome_screen_image.png
    - assets/logo/google_logo.png
    - assets/animations/Splash.json
    - assets/OnBoarding gifs/ONboarding1.json
    - assets/OnBoarding gifs/ONboarding2.json
    - assets/OnBoarding gifs/ONboarding3.json
    - assets/images/egg.png
    - assets/images/milk.png
    - assets/images/mango.png
